version: '3.7'
services:
  redis:
    image: redis:5.0.8-alpine
    expose:
      - 6379
    volumes:
      - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
    networks:
      - datavid19-db-net

networks:
  datavid19-db-net:
    driver: bridge